// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  state

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PageStats ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PageStats ) UnmarshalJSON([]byte) error { return nil }
func ( PageStats ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PageStats ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PageStats *PageStats
