// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  api

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( GameConstants ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GameConstants ) UnmarshalJSON([]byte) error { return nil }
func ( GameConstants ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GameConstants ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GameConstants *GameConstants

func ( LobbyData ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LobbyData ) UnmarshalJSON([]byte) error { return nil }
func ( LobbyData ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LobbyData ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LobbyData *LobbyData

func ( LobbyEntries ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LobbyEntries ) UnmarshalJSON([]byte) error { return nil }
func ( LobbyEntries ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LobbyEntries ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LobbyEntries *LobbyEntries

func ( LobbyEntry ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LobbyEntry ) UnmarshalJSON([]byte) error { return nil }
func ( LobbyEntry ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LobbyEntry ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LobbyEntry *LobbyEntry
