// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  game

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Lobby ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Lobby ) UnmarshalJSON([]byte) error { return nil }
func ( Lobby ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Lobby ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Lobby *Lobby

func ( LobbyRestoreData ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LobbyRestoreData ) UnmarshalJSON([]byte) error { return nil }
func ( LobbyRestoreData ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LobbyRestoreData ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LobbyRestoreData *LobbyRestoreData
