// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package game

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson794297d0DecodeGithubComScribbleRsScribbleRsInternalGame(in *jlexer.Lexer, out *LobbyRestoreData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ShutdownTime":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ShutdownTime).UnmarshalJSON(data))
			}
		case "Lobby":
			if in.IsNull() {
				in.Skip()
				out.Lobby = nil
			} else {
				if out.Lobby == nil {
					out.Lobby = new(Lobby)
				}
				(*out.Lobby).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson794297d0EncodeGithubComScribbleRsScribbleRsInternalGame(out *jwriter.Writer, in LobbyRestoreData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ShutdownTime\":"
		out.RawString(prefix[1:])
		out.Raw((in.ShutdownTime).MarshalJSON())
	}
	{
		const prefix string = ",\"Lobby\":"
		out.RawString(prefix)
		if in.Lobby == nil {
			out.RawString("null")
		} else {
			(*in.Lobby).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LobbyRestoreData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson794297d0EncodeGithubComScribbleRsScribbleRsInternalGame(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LobbyRestoreData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson794297d0EncodeGithubComScribbleRsScribbleRsInternalGame(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LobbyRestoreData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson794297d0DecodeGithubComScribbleRsScribbleRsInternalGame(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LobbyRestoreData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson794297d0DecodeGithubComScribbleRsScribbleRsInternalGame(l, v)
}
func easyjson794297d0DecodeGithubComScribbleRsScribbleRsInternalGame1(in *jlexer.Lexer, out *Lobby) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "LobbyID":
			out.LobbyID = string(in.String())
		case "DrawingTimeNew":
			out.DrawingTimeNew = int(in.Int())
		case "CustomWords":
			if in.IsNull() {
				in.Skip()
				out.CustomWords = nil
			} else {
				in.Delim('[')
				if out.CustomWords == nil {
					if !in.IsDelim(']') {
						out.CustomWords = make([]string, 0, 4)
					} else {
						out.CustomWords = []string{}
					}
				} else {
					out.CustomWords = (out.CustomWords)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.CustomWords = append(out.CustomWords, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Words":
			if in.IsNull() {
				in.Skip()
				out.Words = nil
			} else {
				in.Delim('[')
				if out.Words == nil {
					if !in.IsDelim(']') {
						out.Words = make([]string, 0, 4)
					} else {
						out.Words = []string{}
					}
				} else {
					out.Words = (out.Words)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.Words = append(out.Words, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Players":
			if in.IsNull() {
				in.Skip()
				out.Players = nil
			} else {
				in.Delim('[')
				if out.Players == nil {
					if !in.IsDelim(']') {
						out.Players = make([]*Player, 0, 8)
					} else {
						out.Players = []*Player{}
					}
				} else {
					out.Players = (out.Players)[:0]
				}
				for !in.IsDelim(']') {
					var v3 *Player
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						if v3 == nil {
							v3 = new(Player)
						}
						(*v3).UnmarshalEasyJSON(in)
					}
					out.Players = append(out.Players, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "State":
			out.State = State(in.String())
		case "OwnerID":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OwnerID).UnmarshalText(data))
			}
		case "CurrentWord":
			out.CurrentWord = string(in.String())
		case "WordHints":
			if in.IsNull() {
				in.Skip()
				out.WordHints = nil
			} else {
				in.Delim('[')
				if out.WordHints == nil {
					if !in.IsDelim(']') {
						out.WordHints = make([]*WordHint, 0, 8)
					} else {
						out.WordHints = []*WordHint{}
					}
				} else {
					out.WordHints = (out.WordHints)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *WordHint
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(WordHint)
						}
						(*v4).UnmarshalEasyJSON(in)
					}
					out.WordHints = append(out.WordHints, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "WordHintsShown":
			if in.IsNull() {
				in.Skip()
				out.WordHintsShown = nil
			} else {
				in.Delim('[')
				if out.WordHintsShown == nil {
					if !in.IsDelim(']') {
						out.WordHintsShown = make([]*WordHint, 0, 8)
					} else {
						out.WordHintsShown = []*WordHint{}
					}
				} else {
					out.WordHintsShown = (out.WordHintsShown)[:0]
				}
				for !in.IsDelim(']') {
					var v5 *WordHint
					if in.IsNull() {
						in.Skip()
						v5 = nil
					} else {
						if v5 == nil {
							v5 = new(WordHint)
						}
						(*v5).UnmarshalEasyJSON(in)
					}
					out.WordHintsShown = append(out.WordHintsShown, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "HintsLeft":
			out.HintsLeft = int(in.Int())
		case "HintCount":
			out.HintCount = int(in.Int())
		case "Round":
			out.Round = int(in.Int())
		case "RoundEndTime":
			out.RoundEndTime = int64(in.Int64())
		case "CurrentDrawing":
			if in.IsNull() {
				in.Skip()
				out.CurrentDrawing = nil
			} else {
				in.Delim('[')
				if out.CurrentDrawing == nil {
					if !in.IsDelim(']') {
						out.CurrentDrawing = make([]interface{}, 0, 4)
					} else {
						out.CurrentDrawing = []interface{}{}
					}
				} else {
					out.CurrentDrawing = (out.CurrentDrawing)[:0]
				}
				for !in.IsDelim(']') {
					var v6 interface{}
					if m, ok := v6.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v6.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v6 = in.Interface()
					}
					out.CurrentDrawing = append(out.CurrentDrawing, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ConnectedDrawEventsIndexStack":
			if in.IsNull() {
				in.Skip()
				out.ConnectedDrawEventsIndexStack = nil
			} else {
				in.Delim('[')
				if out.ConnectedDrawEventsIndexStack == nil {
					if !in.IsDelim(']') {
						out.ConnectedDrawEventsIndexStack = make([]int, 0, 8)
					} else {
						out.ConnectedDrawEventsIndexStack = []int{}
					}
				} else {
					out.ConnectedDrawEventsIndexStack = (out.ConnectedDrawEventsIndexStack)[:0]
				}
				for !in.IsDelim(']') {
					var v7 int
					v7 = int(in.Int())
					out.ConnectedDrawEventsIndexStack = append(out.ConnectedDrawEventsIndexStack, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "LastPlayerDisconnectTime":
			if in.IsNull() {
				in.Skip()
				out.LastPlayerDisconnectTime = nil
			} else {
				if out.LastPlayerDisconnectTime == nil {
					out.LastPlayerDisconnectTime = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.LastPlayerDisconnectTime).UnmarshalJSON(data))
				}
			}
		case "Wordpack":
			out.Wordpack = string(in.String())
		case "scoreCalculationIdentifier":
			out.ScoreCalculationIdentifier = string(in.String())
		case "public":
			out.Public = bool(in.Bool())
		case "maxPlayers":
			out.MaxPlayers = int(in.Int())
		case "customWordsPerTurn":
			out.CustomWordsPerTurn = int(in.Int())
		case "clientsPerIpLimit":
			out.ClientsPerIPLimit = int(in.Int())
		case "rounds":
			out.Rounds = int(in.Int())
		case "drawingTime":
			out.DrawingTime = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson794297d0EncodeGithubComScribbleRsScribbleRsInternalGame1(out *jwriter.Writer, in Lobby) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"LobbyID\":"
		out.RawString(prefix[1:])
		out.String(string(in.LobbyID))
	}
	{
		const prefix string = ",\"DrawingTimeNew\":"
		out.RawString(prefix)
		out.Int(int(in.DrawingTimeNew))
	}
	{
		const prefix string = ",\"CustomWords\":"
		out.RawString(prefix)
		if in.CustomWords == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.CustomWords {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Words\":"
		out.RawString(prefix)
		if in.Words == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.Words {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Players\":"
		out.RawString(prefix)
		if in.Players == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Players {
				if v12 > 0 {
					out.RawByte(',')
				}
				if v13 == nil {
					out.RawString("null")
				} else {
					(*v13).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"State\":"
		out.RawString(prefix)
		out.String(string(in.State))
	}
	{
		const prefix string = ",\"OwnerID\":"
		out.RawString(prefix)
		out.RawText((in.OwnerID).MarshalText())
	}
	{
		const prefix string = ",\"CurrentWord\":"
		out.RawString(prefix)
		out.String(string(in.CurrentWord))
	}
	{
		const prefix string = ",\"WordHints\":"
		out.RawString(prefix)
		if in.WordHints == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.WordHints {
				if v14 > 0 {
					out.RawByte(',')
				}
				if v15 == nil {
					out.RawString("null")
				} else {
					(*v15).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"WordHintsShown\":"
		out.RawString(prefix)
		if in.WordHintsShown == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.WordHintsShown {
				if v16 > 0 {
					out.RawByte(',')
				}
				if v17 == nil {
					out.RawString("null")
				} else {
					(*v17).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"HintsLeft\":"
		out.RawString(prefix)
		out.Int(int(in.HintsLeft))
	}
	{
		const prefix string = ",\"HintCount\":"
		out.RawString(prefix)
		out.Int(int(in.HintCount))
	}
	{
		const prefix string = ",\"Round\":"
		out.RawString(prefix)
		out.Int(int(in.Round))
	}
	{
		const prefix string = ",\"RoundEndTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.RoundEndTime))
	}
	{
		const prefix string = ",\"CurrentDrawing\":"
		out.RawString(prefix)
		if in.CurrentDrawing == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.CurrentDrawing {
				if v18 > 0 {
					out.RawByte(',')
				}
				if m, ok := v19.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v19.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v19))
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ConnectedDrawEventsIndexStack\":"
		out.RawString(prefix)
		if in.ConnectedDrawEventsIndexStack == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.ConnectedDrawEventsIndexStack {
				if v20 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v21))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"LastPlayerDisconnectTime\":"
		out.RawString(prefix)
		if in.LastPlayerDisconnectTime == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.LastPlayerDisconnectTime).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"Wordpack\":"
		out.RawString(prefix)
		out.String(string(in.Wordpack))
	}
	{
		const prefix string = ",\"scoreCalculationIdentifier\":"
		out.RawString(prefix)
		out.String(string(in.ScoreCalculationIdentifier))
	}
	{
		const prefix string = ",\"public\":"
		out.RawString(prefix)
		out.Bool(bool(in.Public))
	}
	{
		const prefix string = ",\"maxPlayers\":"
		out.RawString(prefix)
		out.Int(int(in.MaxPlayers))
	}
	{
		const prefix string = ",\"customWordsPerTurn\":"
		out.RawString(prefix)
		out.Int(int(in.CustomWordsPerTurn))
	}
	{
		const prefix string = ",\"clientsPerIpLimit\":"
		out.RawString(prefix)
		out.Int(int(in.ClientsPerIPLimit))
	}
	{
		const prefix string = ",\"rounds\":"
		out.RawString(prefix)
		out.Int(int(in.Rounds))
	}
	{
		const prefix string = ",\"drawingTime\":"
		out.RawString(prefix)
		out.Int(int(in.DrawingTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Lobby) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson794297d0EncodeGithubComScribbleRsScribbleRsInternalGame1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Lobby) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson794297d0EncodeGithubComScribbleRsScribbleRsInternalGame1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Lobby) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson794297d0DecodeGithubComScribbleRsScribbleRsInternalGame1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Lobby) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson794297d0DecodeGithubComScribbleRsScribbleRsInternalGame1(l, v)
}
